
options = input("\nPress 1 for Moving Average Backtesting Strategy\nPress 2 for RSI Backtesting Strategy:\n  ")

if options == "1":
    print("Moving Averages")
    binance_data = vbt.BinanceData.download(pair,start=start,end=end,interval=interval)
    print(binance_data.get())
    up=int(input("Enter window range example 2: "))
    end=int(input("Enter window range example 101:"))
    windows = np.arange(up, end)
    fast_ma, slow_ma = vbt.MA.run_combs(binance_data.get('Close'), window=windows, r=2, short_names=['fast', 'slow'])
    entries = fast_ma.ma_crossed_above(slow_ma)
    exits = fast_ma.ma_crossed_below(slow_ma)
    fee=float(input("fee value: 0.001 "))
    print(fee)
    freq=input("freq: 1D ")
    pf_kwargs = dict(size=np.inf, fees=fee, freq=freq)
    pf = vbt.Portfolio.from_signals(binance_data.get('Close'), entries, exits, **pf_kwargs)
    pf[(10, 20, pair)].plot().show()
    print(pf[(10, 20, pair)].stats())
else:
    print("RSI")
    rsi=vbt.RSI.run(binance_data.get('Close'))
    rsi_entries=int(input("Enter RSI Below:30 "))
    rsi_exit=int(input("Enter RSI Above:70 "))
    entries=rsi.rsi_below(rsi_entries)
    exits = rsi.rsi_above(rsi_exit)
    initialCash=int(input("initial cash : 1000 "))
    pf=vbt.Portfolio.from_signals(binance_data.get('Close'),entries,exits,init_cash=initialCash)
    pf.plot().show()
    print(pf.stats())