# Emojis for messages
e_set = "🛠 " # setting
e_sat = "🛰 " # sat
e_lin = "🐧 " # linux
e_kak = "💩 " # kaka
e_fie = "🎊 " # fiesta
e_mon = "🤑 " # money
e_sac = "💰 " # saca
e_mov = "📱 " # movil
e_ato = "⚛️ " # atom
e_tra = "💱 " # trad
e_ant = "📡 " # antena
e_rok = "🚀 " # roket
e_ala = "⏰ " # alarm
e_bot = "🤖 " # bot
e_pyt = "🐍 " # pyt
e_err = "‼  "  # Error
e_wit = "⏳ "  # Wait
e_fns = "🏁 "  # Finished
e_ntf = "🔔 "  # Notify
e_bgn = "✨ "  # Beginning
e_cnc = "❌ "  # Cancel
e_top = "👍 "  # Top
e_dne = "✔ "  # Done
e_fld = "✖ "  # Failed
e_gby = "👋 "  # Goodbye
e_qst = "❓ "  # Question
e_adw = "⬇️ "  # dwon
e_aup = "⬆️ "  # up
e_upt = "📈 "  # chart up
e_dwt = "📉 "  # chart dw
e_nin = "🥷 "  # ninja
e_cal = "🗓️ "  #calendar
e_red = "🔴 "  #circle red
e_gre = "🟢 "  #circle green
